AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ScoringFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          GEMINI_API_KEY: !Ref GeminiApiKey
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ScoreAssessment:
          Type: Api
          Properties:
            Path: /score
            Method: post
        OptionsRequest:
          Type: Api
          Properties:
            Path: /score
            Method: options

Parameters:
  GeminiApiKey:
    Type: String
    NoEcho: true
    Description: Gemini API Key for evaluation 